---
# Install and configure Minio Server
- block:
    - name: Create minio user
      user:
        name: "{{ minio_user }}"
        home: "{{ minio_home }}"
        shell: /sbin/nologin

    - name: Ensure that minio directories are created
      file:
        path: "{{ minio_dir }}"
        state: directory
        mode: 0750
        owner: "{{ minio_user }}"
        group: "{{ minio_group }}"
      loop:
        - "{{ minio_home }}"
        - "{{ minio_home }}/bin"
        - "{{ minio_data_path }}"
        - "{{ minio_home }}/.minio"
        - "{{ minio_home }}/.minio/certs"
        - "{{ minio_data_path }}/.minio.sys"
        - "{{ minio_data_path }}/.minio.sys/config"
      loop_control:
        loop_var: minio_dir
      notify: Restart Minio

    - name: Copy minio binary file
      get_url:
        url: "{{ minio_package_source }}"
        dest: "{{ minio_home }}/bin/minio"
        mode: +x
        owner: "{{ minio_user }}"
        group: "{{ minio_group }}"
      register: file_downloaded
      retries: 15
      delay: 5
      until: file_downloaded is succeeded
      notify: Restart Minio

    - name: Copy minio templates
      template:
        src: "{{ conf_item.src }}.j2"
        dest: "{{ conf_item.dest }}"
        backup: True
        mode: 0644
        owner: "{{ conf_item.user }}"
      loop:
        - src: minio.conf
          dest: "{{ minio_home }}/minio.conf"
          user: "{{ minio_user }}"
        - src: minio.service
          dest: /etc/systemd/system/minio.service
          user: root
      loop_control:
        loop_var: conf_item
      notify: Restart Minio
  become: True
