---
# tasks file for aem-minio

- block:
  - name: Create minio user
    user:
      name: '{{ minio_user }}'
      home: '{{ minio_home }}'
      shell: /sbin/nologin

  - name: Ensure that minio directories are created
    file:
      path: '{{ minio_dir }}'
      state: directory
      mode: 0750
      owner: '{{ minio_user }}'
      group: '{{ minio_group }}'
    loop:
      - '{{ minio_home }}'
      - '{{ minio_home }}/bin'
      - '{{ minio_data_path }}'
    loop_control:
      loop_var: minio_dir

  - name: check if binary file already exists
    stat:
      path: '{{ minio_home }}/bin/minio'
    register: bin_file

  - name: Copy minio binary file
    get_url:
      url: '{{ minio_package_source }}'
      dest: '{{ minio_home }}/bin/minio'
      mode: +x
      owner: '{{ minio_user }}'
      group: '{{ minio_group }}'
    register: file_downloaded
    retries: 15
    delay: 5
    until: "'OK' in file_downloaded.msg"
    when: not bin_file.stat.exists

  - name: Copy minio templates
    template:
      src: '{{ conf_item.src }}.j2'
      dest: '{{ conf_item.dest }}'
      backup: True
      mode: 0644
      owner: '{{ conf_item.user }}'
    loop:
      - src: minio.conf
        dest: '{{ minio_home }}/minio.conf'
        user: '{{ minio_user }}'
      - src: minio.service
        dest: /etc/systemd/system/minio.service
        user: root
    loop_control:
      loop_var: conf_item

  - name: Start Minio
    service:
      name: minio
      state: started
      enabled: True

  - name: Copy minio config.json
    template:
      src: config.json.j2
      dest: '{{ minio_home }}/data/.minio.sys/config/config.json'
      backup: True
      mode: 0644
      owner: '{{ minio_user }}'
    notify:
    - Restart Minio

  become: True
