---
# tasks file for aem-minio

- name: Create minio user
  user:
    name: '{{ minio_user }}'
    home: '{{ minio_home }}'
    shell: /sbin/nologin
  become: True

- name: Ensure minio home directory is created
  file:
    path: '{{ minio_home }}'
    state: directory
    mode: 0750
    owner: '{{ minio_user }}'
    group: '{{ minio_group }}'
  become: True

- name: Ensure minio bin directory is created in {{ minio_home }}
  file:
    path: "{{ minio_home }}/bin"
    state: directory
    mode: 0750
    owner: '{{ minio_user }}'
    group: "{{ minio_group }}"
  become: True

- name: Ensure minio data directory is created in {{ minio_home }}
  file:
    path: "{{ minio_home }}/data"
    state: directory
    mode: 0750
    owner: '{{ minio_user }}'
    group: "{{ minio_group }}"
  become: True

- name: Copy minio binary file
  get_url:
    url: "{{ minio_package_source }}"
    dest: "{{ minio_home }}/bin/minio"
    mode: +x
  become: True

- name: Copy minio config
  template:
    src: "minio.conf.j2"
    dest: '{{ minio_home }}/minio.conf'
    backup: True
    mode: 0644
    owner: '{{ minio_user }}'
  become: True

- name: Copy minio service
  template:
    src: "minio.service.j2"
    dest: /etc/systemd/system/minio.service
    backup: True
    mode: 0644
  become: True
  notify:
    - Start Minio

- meta: flush_handlers

- name: Copy minio config.json
  template:
    src: config.json.j2
    dest: '{{ minio_home }}/data/.minio.sys/config/config.json'
    backup: True
    mode: 0644
    owner: '{{ minio_user }}'
  become: True
  notify:
    - Restart Minio

- meta: flush_handlers
