---
# tasks file for minio

- name: Install
  include_tasks: install.yml

- name: SSL preparation
  include_tasks: "ssl/{{ ansible_system }}.yml"
  when:
    - minio_enable_ssl

- name: Start Minio
  service:
    name: minio
    state: started
    enabled: True
  become: True
  notify: Check Minio on '{{ minio_connection_type }}'
