---
# handlers file for minio

- name: Restart Minio
  service:
    name: minio
    state: restarted
  notify: Wait for Minio
  become: True

- name: Wait for Minio
  uri:
    url: "{{ minio_connection_type }}://{{ minio_hostname }}:{{ minio_http_port }}/minio/login"
    status_code: 200
    headers:
      User-Agent: 'Mozilla/5.0'
    validate_certs: False
  register: login_page
  until: login_page.status == 200
  retries: 10
  delay: 1
