---
# handlers file for minio

- name: Restart Minio
  service:
    name: minio
    state: restarted
  notify: Check Minio on '{{ minio_connection_type }}'
  become: True

- name: Check Minio on '{{ minio_connection_type }}'
  uri:
    url: '{{ minio_connection_type }}://{{ minio_hostname }}:{{ minio_http_port }}/minio/login'
    status_code: 200
    headers:
      User-Agent: 'Mozilla/5.0'
    validate_certs: False
  register: login_page
  until: login_page.status == 200
  retries: 10
  delay: 1
