---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint: |
  yamllint -c .yamllint .
  ansible-lint -c .ansible-lint
platforms:
  # - name: test-docker-centos7-minio
  #   image: ghcr.io/pavelpikta/docker-systemd/centos7:latest
  #   privileged: True
  #   # published_ports:
  #   #   - "0.0.0.0:9000:9000/tcp"
  #   #   - "0.0.0.0:9001:9001/tcp"
  #   groups:
  #     - rhel_family
  - name: test-docker-ubuntu1804-minio
    image: ghcr.io/pavelpikta/docker-systemd/ubuntu-18.04:latest
    privileged: True
    security_opts:
      - seccomp=unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    groups:
      - debian_family
provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
  playbooks:
    verify: ../resources/tests/verify.yml
scenario:
  name: default
verifier:
  name: ansible
