---
# Generate selfsigned key

- block:
    - name: Enable EPEL repository
      yum:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
        state: present
      register: package_install
      until: package_install is succeeded
      when: ansible_os_family == 'RedHat'

    - name: Load variables for OS family
      include_vars: "{{ ansible_os_family }}.yml"

    - name: Install requirements
      package:
        name: "{{ requirements }}"
        state: present
      register: package_install
      until: package_install is succeeded

    - name: Install pip packages
      pip:
        name:
          - pyOpenSSL
        state: present
        extra_args: --upgrade
      register: package_install
      until: package_install is succeeded

    - name: Create private certificate
      openssl_privatekey:
        path: "{{ minio_key_path }}/private.key"
        size: "{{ minio_ssl_key_size | int }}"
        owner: "{{ minio_user }}"

    - name: Create CSR
      openssl_csr:
        path: "/tmp/{{ minio_ssl_cert_file_name }}.csr"
        privatekey_path: "{{ minio_key_path }}/private.key"
        common_name: "{{ minio_ca_domain }}"
        owner: "{{ minio_user }}"
        subject_alt_name: "IP:{{ ansible_default_ipv4.address }}"

    - name: Create certificates for keystore
      openssl_certificate:
        csr_path: "/tmp/{{ minio_ssl_cert_file_name }}.csr"
        path: "{{ minio_cert_path }}/public.crt"
        privatekey_path: "{{ minio_key_path }}/private.key"
        provider: "{{ minio_ssl_certificate_provider }}"
        owner: "{{ minio_user }}"
      notify: Restart Minio
  become: true
