---
name: CI

on:
  push:
  pull_request:
  release:
    types:
      - created

env:
  REGISTRY: ghcr.io
  ANSIBLE_FORCE_COLOR: 1
  PY_COLORS: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    container: ghcr.io/pavelpikta/docker-ansible-ci:2.9
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lints
        run: |
          yamllint . -c .yamllint
          ansible-lint -c .ansible-lint

  molecule:
    needs: lint
    runs-on: ubuntu-latest
    container: ghcr.io/pavelpikta/docker-ansible-ci:2.9

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Molecule
        run: molecule test -s default
